export const KENYAN_TOWNS = [
  'Nairobi',
  'Mombasa',
  'Kisumu',
  'Nakuru',
  'Eldoret',
  'Kericho',
  'Nyeri',
  'Muranga',
  'Thika',
  'Nanyuki',
  'Kitale',
  'Bungoma',
  'Kakamega',
  'Kisii',
  'Homabay',
  'Migori',
  'Machakos',
  'Voi',
  'Mwingi',
  'Embu',
  'Meru',
  'Isiolo',
  'Garissa',
  'Wajir',
  'Mandera',
  'Lamu',
  'Malindi',
  'Kilifi',
  'Diani',
  'Kwale',
  'Kajiado',
  'Narok',
  'Bomet',
  'Kapsabet',
  'Uasin Gishu',
  'Trans Nzoia',
  'West Pokot',
  'Samburu',
  'Laikipia',
  'Tharaka Nithi',
  'Kitui',
  'Makueni',
  'Taita Taveta',
  'Kisumu County',
  'Siaya',
  'Rarieda',
  'Nyamira',
  'Kilgoris',
  'Suna',
  'Rachuonyo',
]

export const filterTowns = (input: string): string[] => {
  if (!input.trim()) return []
  return KENYAN_TOWNS.filter((town) =>
    town.toLowerCase().includes(input.toLowerCase())
  ).slice(0, 8)
}
